# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

ADD src/main/docker/entrypoint-web.sh entrypoint.sh

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install --silent

# start app
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 9060 3001 9000
